[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"

[[services]]
name = "frontend" 
source = "frontend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "nginx -g 'daemon off;'"